### PR TITLE
SCSS colors to Javascript

### PR DESCRIPTION
**Pull request by Matt-Butler**
SCSS color variables are now available in JS.

Updated configuration to match existing repos.

@cerner/terra

### CODE REVIEW

**Comment by Matt-Butler** [comment]
I'll leave this open for a few days until the color discussion is finished. This should be easy to modify after we have a solid list of scss colors.

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-legacy-theme/issues/5

**Comment by mhemesath** [comment]
Can I propose something different. Instead of having the variables in SCSS and having a task to generate JSON. Can we have the colors in JSON and have a task to convert them to SCSS?

**Comment by mjhenkes** [comment]
@mhemesath, out of curiosity, what is the benefit of reversing it?

**Comment by mhemesath** [comment]
The library being used to convert the colors has its limitations and not
using it is 1 less dependency.

**Comment by Matt-Butler** [comment]
Actually, thinking about this more..... I'm not sure if this will work with theming.

We cannot have a dependency/devDependency on a theme, therefore I can't import `terra-legacy-theme`.
```
LegacyTheme.scheme['$terra-text-color-10']
``

**Comment by mhemesath** [comment]
So, themes will likely have to be applied via a SCSS loaded override. We could create a specialized theme loader which would take a JSON file and convert it to SCSS to apply the theme dynamically to sass files.

As for JavaScript.. My thoughts are we have a single Theme package. So you can do `Theme.concept.text_color_10`. The theme package may or may not have a default theme.. i don't care so much about that. What it will have is the ability to update the Theme. So I can do `Theme.load({concepts: {text_color_10: '#000' }})` and from then on the text color will be black. How we load themes can be done a few ways.

1. We create a plugin which does this in webpack build. I don't know exactly how to do this but imagine its possible.
2. The theme package checks for a global object of `TERRA_THEME` and if it sees it.. it will load that theme immediately.

Anyway, we can meet and chat about this, these are some of my initial thoughts on it

**Comment by mjhenkes** [comment]
With the the above approach, would it be possible to change themes on the fly in a deployed app?

**Comment by Matt-Butler** [comment]
> With the the above approach, would it be possible to change themes on the fly in a deployed app?

No, we cannot update stylesheets during runtime. Theme currently needs to be part of the webpack configuration. Our bundled css is built out before the application starts.

**Comment by Matt-Butler** [comment]
I am going to close this PR until we finalize our color theming strategy.

**Pull request closed without merging**
